### ISSUE TITLE
Support monorepo: custom tailwind config path

### ISSUE THREAD

**Issue by nhducit** [kalimahapps/vscode-tailwind-config-viewer#4]
Thank you for the useful plugin. It would be great if this plugin supports the monorepo set up which the tailwind.config.js file is not in the root folder. e.g. support provide the custom path for the tailwind config file

**Comment by abdul-alhasany** [comment]
Sure. Do you have a monorepo I can test on?

**Comment by abdul-alhasany** [comment]
This is fixed in version 0.0.5.

**Comment by zeckdude** [comment]
@abdul-alhasany Thanks for creating such an awesome plugin! I'm in the same boat where my `tailwind.config.js` file is at `web/tailwind.config.js`. Since it's nested one level, I am using the following settings for the plugin:

```
{
  "tailwindConfigViewer.workspacePath": "./web"
}
````

Unfortunately the plugin can't find my config file though. Any ideas if I'm doing something wrong? 

I'm using tailwind 3.3.1

<img width="254" alt="Screen Shot 2023-05-18 at 3 10 57 PM" src="https://github.com/kalimahapps/vscode-tailwind-config-viewer/assets/947856/9ef5fe05-4d6c-4465-8313-acdcc7dff3f1">
<img width="404" alt="Screen Shot 2023-05-18 at 3 13 17 PM" src="https://github.com/kalimahapps/vscode-tailwind-config-viewer/assets/947856/f349f3fb-9518-4661-9621-a074435425b8">

**Comment by abdul-alhasany** [comment]
@zeckdude You are right. The last fix was only for absolute paths. I updated the extension now. In 0.0.6 you can use relative paths like in your example.

Try the new version and let me know.

**Comment by zeckdude** [comment]
That worked amazing! Thank you so much!!!

**Comment by zeckdude** [comment]
@abdul-alhasany That worked amazing! Thank you!!!

**Comment by abdul-alhasany** [comment]
@zeckdude Great. I will close this ticket. If you liked the extension please rate in marketplace. Let me know if you face further issues.
